### ISSUE TITLE
cyclonedx-py fails with Type 'encoding' error

### ISSUE THREAD

**Issue by A30003153** [CycloneDX/cyclonedx-python#26]
I am getting following error: Pasting little extra information for context and clarity:

2019-10-28T23:20:16.1096691Z Successfully built requirements-parser
2019-10-28T23:20:16.1102564Z Installing collected packages: requirements-parser, urllib3, certifi, chardet, idna, requests, elementpath, xmlschema, six, attrs, pyparsing, packaging, packageurl-python, cyclonedx-bom
2019-10-28T23:20:17.1299044Z Successfully installed attrs-19.3.0 certifi-2019.9.11 chardet-3.0.4 cyclonedx-bom-0.3.2 elementpath-1.2.2 idna-2.8 packageurl-python-0.8.7 packaging-19.1 pyparsing-2.4.2 requests-2.22.0 requirements-parser-0.1.0 six-1.12.0 urllib3-1.25.6 xmlschema-1.0.14
2019-10-28T23:20:17.3477654Z You are using pip version 8.1.1, however version 19.3.1 is available.
2019-10-28T23:20:17.3479418Z You should consider upgrading via the 'pip install --upgrade pip' command.
2019-10-28T23:20:17.3702738Z + pip show cyclonedx-bom
2019-10-28T23:20:17.8761536Z ---
2019-10-28T23:20:17.8765697Z Metadata-Version: 2.1
2019-10-28T23:20:17.8766202Z Name: cyclonedx-bom
2019-10-28T23:20:17.8766413Z Version: 0.3.2
2019-10-28T23:20:17.8769902Z Summary: CycloneDX software bill-of-material (SBOM) generation utility
2019-10-28T23:20:17.8770437Z Home-page: https://github.com/CycloneDX/cyclonedx-python
2019-10-28T23:20:17.8770629Z Author: Steve Springett
2019-10-28T23:20:17.8774491Z Author-email: steve.springett@owasp.org
2019-10-28T23:20:17.8774946Z Installer: pip
2019-10-28T23:20:17.8775323Z License: Apache-2.0
2019-10-28T23:20:17.8778455Z Location: /home/vsts/.local/lib/python2.7/site-packages
2019-10-28T23:20:17.8779012Z Requires: requirements-parser, requests, xmlschema, packaging, packageurl-python
2019-10-28T23:20:17.8779198Z Classifiers:
2019-10-28T23:20:17.8782981Z   Intended Audience :: Developers
2019-10-28T23:20:17.8783440Z   Intended Audience :: Information Technology
2019-10-28T23:20:17.8783608Z   Intended Audience :: Legal Industry
2019-10-28T23:20:17.8786665Z   Intended Audience :: System Administrators
2019-10-28T23:20:17.8787179Z   Topic :: Security
2019-10-28T23:20:17.8787358Z   Topic :: Software Development
2019-10-28T23:20:17.8790255Z   Topic :: System :: Software Distribution
2019-10-28T23:20:17.8791144Z   License :: OSI Approved :: Apache Software License
2019-10-28T23:20:17.8791334Z   Programming Language :: Python :: 2.7
2019-10-28T23:20:17.8795009Z Entry-points:
2019-10-28T23:20:17.8795283Z   [console_scripts]
2019-10-28T23:20:17.8795699Z   cyclonedx-py = cyclonedx.cli.generateBom:main
2019-10-28T23:20:18.0775388Z You are using pip version 8.1.1, however version 19.3.1 is available.
2019-10-28T23:20:18.0777645Z You should consider upgrading via the 'pip install --upgrade pip' command.
2019-10-28T23:20:18.0986202Z + echo '/usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:~/.local/bin'
2019-10-28T23:20:18.0988032Z + cyclonedx-py
2019-10-28T23:20:18.0988825Z /usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:~/.local/bin
2019-10-28T23:20:24.7208894Z Input file: requirements.txt
2019-10-28T23:20:24.7210400Z Output BOM: bom.xml
2019-10-28T23:20:24.7211081Z Traceback (most recent call last):
2019-10-28T23:20:24.7212274Z   File "/home/vsts/.local/bin/cyclonedx-py", line 11, in <module>
2019-10-28T23:20:24.7212852Z     sys.exit(main())
2019-10-28T23:20:24.7213651Z   File "/home/vsts/.local/lib/python2.7/site-packages/cyclonedx/cli/generateBom.py", line 137, in main
2019-10-28T23:20:24.7214486Z     with open(args.input_file, 'r', encoding=result['encoding']) as fd:
2019-10-28T23:20:24.7215292Z TypeError: 'encoding' is an invalid keyword argument for this function
[requirements.txt](https://github.com/CycloneDX/cyclonedx-python/files/3781882/requirements.txt)

**Comment by A30003153** [comment]
Someone suggested to use Python3 and I tried that as well but didn't help.

Also have seen some suggestions around adding an 'import io' and using io.open insteand of open.
@stevespringett

**Comment by stevespringett** [comment]
The python3 method of opening files using an encoding method is used. Therefore this project is not compatible with python 2.7.

I cannot reproduce on python 3.x
