### ISSUE TITLE
Requirements file referencing local packages

### ISSUE THREAD

**Issue by Jonas-vdb** [CycloneDX/cyclonedx-python#284]
**Version**
cyclonedx-bom==1.5.3

**Executed command**
`cyclonedx-py -r -o bom.xml` 

**Use case**
Our requirements.txt file references other local python packages. Example of requirements file:

```
../local-python-package1
../local-python-package2
../local-python-package3

package1==0.0.0
package2==0.0.0
package3==0.0.0
```
**Exception**
```
Traceback (most recent call last):
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jvdb/repos/venv-tmp/lib/python3.6/site-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)
```

**Comment by madpah** [comment]
Thanks for the report @Jonas-vdb - we'll look into addressing this in the child library [`cyclonedx-python-lib`](https://github.com/CycloneDX/cyclonedx-python-lib).

**Comment by madpah** [comment]
@Jonas-vdb - after a quick review, it appears that the root cause is an internal package/method in Python that does not support parsing `requirements.txt` file lines that reference local packages.

We see two options, and we are keen to get your views based on your use case:

1. We can skip/ignore any locally referenced packages in `requirements.txt` files. This would be valid in once sense as we would not know the package version (given your example above), and `version` is a mandatory field for defining a `Component` in a CyloneDX BOM
2. Depending on your workflow/use case, could you not generate your CycloneDX BOM after you have installed your Python Application into a temporary Python Environment? If so, you could use the `EnvironmentParser` functionality which would:
   1.  Not suffer from the same parse error
   2. The resulting CycloneDX BOM would also include your referenced local packages (i.e a more complete and accurate picture than the first option)
   
Appreciate your feedback, thanks.

FYI: @jkowalleck

**Comment by Jonas-vdb** [comment]
Thank you for your quick review. 

Our current workaround is to remove those packages programmatically and append the content of the requirement files of the linked packages.

I do agree that generating the CycloneDX BOM file from the installed application is the better option. Even though the workaround works at this point, we will probably update our implementation to use the EnvironmentParser.

**Comment by jkowalleck** [comment]
the requirements-parser in use in this project is not the same `pip install -r` uses.
For a simple reason: this project is not pip. but it supports the output of `pip freeze` - see  https://github.com/CycloneDX/cyclonedx-python/#requirements

:+1: I welcome your remark very much, @Jonas-vdb : https://github.com/CycloneDX/cyclonedx-python/issues/284#issuecomment-995119137
> I do agree that generating the CycloneDX BOM file from the installed application is the better option. Even though the workaround works at this point, we will probably update our implementation to use the EnvironmentParser.

just as the README of this project states: 
* use `--environment` will find all installed/shipped packages and is most likely the best solution for most users.
* every other option is a filter/modification of the actual SBoM and you need to use it as described in the readme.
  and regarding requirements-file  it clearly described to use `pip freeze`

that being said:
does the `--environment` switch work for you, @Jonas-vdb ? 
does it find your local packages properly and add them to the SBoM ?

**Comment by AnalogJ** [comment]
fyi, this is the same error that occurs when the requirements.txt file contains `-e .`

**Comment by jkowalleck** [comment]
for discussions, feel free to switch to https://github.com/CycloneDX/cyclonedx-python/discussions/319
