### ISSUE TITLE
Support for UTF16 parsing

### ISSUE THREAD

**Issue by ayeks** [CycloneDX/cyclonedx-python#3]
When attempting to parse a UTF16 requirements txt the tool throws an UnicodeDecodeError. One solution could be to ignore UTF16 chars with `with open(path, encoding="utf8", errors='ignore') as f:` ([source](https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in)).

The complete message:
```
+ cyclonedx-py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requirements/parser.py", line 19, in parse
    if not isinstance(reqstr, basestring):
NameError: name 'basestring' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cyclonedx-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cyclonedx/cli/generateBom.py", line 48, in main
    for req in requirements.parse(fd):
  File "/usr/local/lib/python3.6/site-packages/requirements/parser.py", line 24, in parse
    reqstr = reqstr.read()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Input file: requirements.txt
Output BOM: bom.xml
Generating CycloneDX BOM
```

The workaround is to generate the requirements.txt with pip again to get rid of the UTF16.
```
python3 -m venv venv
source venv/bin/activate
pip freeze > requirements.txt
deactivate
```

However, it would be nice if cyclonedx-python can handle UTF16 like pip.

**Comment by coderpatros** [comment]
Hi @ayeks this is working for me now in the latest release v0.4.0.

But let us know if you continue to have issues with UTF-16.
