### ISSUE TITLE
Support for locally referenced packages in `requirements.txt`

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python#315]

**Comment by mostafa** [comment]
Perfect! Just give me a nod when you release next week. Alternatively, I can start working on the feature off the branch you want to merge and then rebase from the default branch after merging. Up to you! 🙂

**Comment by madpah** [comment]
Hey @mostafa - we've released `cyclonedx-python` `3.0.0` today. Would be awesome to get a PR to move to `requirements-parser` as you suggested.

Thanks!

**Comment by mostafa** [comment]
@madpah I am trying to test the library locally but ran into an issue:
The tests fail because the [method signature](https://github.com/CycloneDX/cyclonedx-python-lib/blob/a4af3dccbddf4ea91b277746d2305fadf6078ed8/cyclonedx/parser/__init__.py#L62) of `BaseParser.get_components` returns [`self._components`](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/parser/__init__.py#L48) which is a `List[Component]`, but the code expects a `set`, so it can `add` to it; a method that is not supported on a `list`:

```bash
======================================================================
ERROR: test_conda_list_explicit_md5 (tests.test_parser_conda.TestCondaParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_conda.py", line 46, in test_conda_list_explicit_md5
    parser = CondaListExplicitParser(conda_data=conda_list_ouptut_fh.read())
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 41, in __init__
    self._conda_packages_to_components()
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 68, in _conda_packages_to_components
    c.external_references.add(ExternalReference(
AttributeError: 'list' object has no attribute 'add'
```

Is this something you're aware of? Or should I create an issue?

**Comment by madpah** [comment]
@mostafa - not aware of this issue, and concerned as tests are passing in CI too. If you can raise an Issue for this, I’ll investigate later today.

Thanks again 🙏

**Comment by madpah** [comment]
Tests passing here: https://github.com/CycloneDX/cyclonedx-python/runs/5277735507?check_suite_focus=true

**Comment by mostafa** [comment]
@madpah I saw the passing tests, which is why I am confused, but I'll create a separate issue for it.

**Comment by llamahunter** [comment]
We don't have locally referenced packages, but we do have a private pypi repo, and it appears that the `pkg_resources` library simply isn't up to the task of parsing a full pip `requirements.txt` file, including the `--index-url` directives.
https://github.com/CycloneDX/cyclonedx-python/issues/318

**Comment by jkowalleck** [comment]
Tool might not supports all the features people use in their `requirements.txt`.
the capability is a file that is created by `pip freeze`.  @llamahunter

**Comment by jkowalleck** [comment]
just for the record: I dont have any opinion about a particular requirements-file-parser. Unlike @madpah I never dug deep into this topic.

----

regarding 

> Also, the pip-requirements-parser package has only one API, which is RequirementsFile.from_file, and if we want to parse requirements file as a string, we need to make our own API using internal APIs of the package or get rid of our string processing altogether.

For string input we could create a temp file and run `RequirementsFile.parse`/`RequirementsFile.from_file` on thes temp file with `include_nested=False`, as relative paths are assumtions out of thin air based on current working dir and stuff.
For direct file input we would set `include_nested=true`, as relative paths from that file could be resolved.

**Comment by llamahunter** [comment]
> please open another issue, if you want to request another feature for the requirements parser.
> this issue is about local packages.

I already did. See my post above and https://github.com/CycloneDX/cyclonedx-python/issues/318

**Comment by jkowalleck** [comment]
for discussions, feel free to switch to https://github.com/CycloneDX/cyclonedx-python/discussions/319

**Comment by mostafa** [comment]
One more thing that's definitely off-topic:
I see lots of `<file>.close()` lines throughout the project inside context managers, which is redundant because the file itself is actually being opened inside the body of a [`with` statement](https://docs.python.org/3/reference/compound_stmts.html#with) that is a [context manager](https://docs.python.org/3/reference/datamodel.html#context-managers) and will close the file automatically, even if an exception occurs inside the body.
