### ISSUE TITLE
[BUG] Method signature doesn't match

### ISSUE THREAD

**Issue by mostafa** [CycloneDX/cyclonedx-python#317]
As discussed [here](https://github.com/CycloneDX/cyclonedx-python/issues/315#issuecomment-1047667516),  I forked the master branch and tried to test the library locally with Python 3.9.6 but ran into an issue:
The tests fail because the [method signature](https://github.com/CycloneDX/cyclonedx-python-lib/blob/a4af3dccbddf4ea91b277746d2305fadf6078ed8/cyclonedx/parser/__init__.py#L62) of `BaseParser.get_components` returns [`self._components`](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/parser/__init__.py#L48) which is a `List[Component]`, but the code expects a `set`, so it can `add` to it; a method that is not supported on a `list`. There are 4 instances of this issue in various places. The following is an example of the tests that fail because of this error:

```bash
======================================================================
ERROR: test_conda_list_explicit_md5 (tests.test_parser_conda.TestCondaParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_conda.py", line 46, in test_conda_list_explicit_md5
    parser = CondaListExplicitParser(conda_data=conda_list_ouptut_fh.read())
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 41, in __init__
    self._conda_packages_to_components()
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 68, in _conda_packages_to_components
    c.external_references.add(ExternalReference(
AttributeError: 'list' object has no attribute 'add'
```

Given a virtualenv, it works fine, though. 😕 It might be some dependency mismatch on my global env, but other than that, looking at the code seems to suggest otherwise.

**Comment by jkowalleck** [comment]
> This is a dependency issue.

from which version?
we might need to modify the dependency version constraints of this _cyclonedx-python_.

**Comment by mostafa** [comment]
@jkowalleck

I used these versions:

```text
cyclonedx-bom: latest master (install 3.0.0)
cyclonedx-python-lib: 2.0.0
Python: 3.9.6 (via pyenv)
Poetry:  1.1.13
```
And ran `poetry install` in the cloned git repo of `cyclonedx-bom` on my machine, which installed the dependencies globally. Then I ran `python -m unittest`, which resulted in the errors:

<details>
  <summary>Results of running `python -m unittest`</summary>

```bash
$ python -m unittest
EEEEEE...s........
======================================================================
ERROR: test_conda_list_explicit_md5 (tests.test_parser_conda.TestCondaParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_conda.py", line 46, in test_conda_list_explicit_md5
    parser = CondaListExplicitParser(conda_data=conda_list_ouptut_fh.read())
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 41, in __init__
    self._conda_packages_to_components()
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 68, in _conda_packages_to_components
    c.external_references.add(ExternalReference(
AttributeError: 'list' object has no attribute 'add'

======================================================================
ERROR: test_conda_list_json (tests.test_parser_conda.TestCondaParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_conda.py", line 31, in test_conda_list_json
    parser = CondaListJsonParser(conda_data=conda_list_ouptut_fh.read())
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 41, in __init__
    self._conda_packages_to_components()
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/conda.py", line 68, in _conda_packages_to_components
    c.external_references.add(ExternalReference(
AttributeError: 'list' object has no attribute 'add'

======================================================================
ERROR: test_simple (tests.test_parser_environment.TestEnvironmentParser)
@todo This test is a vague as it will detect the unique environment where tests are being executed -
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_environment.py", line 33, in test_simple
    parser = EnvironmentParser()
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/environment.py", line 71, in __init__
    c.licenses.add(LicenseChoice(license_expression=i_metadata['License']))
AttributeError: 'list' object has no attribute 'add'

======================================================================
ERROR: test_simple (tests.test_parser_pipenv.TestPipEnvParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_pipenv.py", line 30, in test_simple
    parser = PipEnvFileParser(pipenv_lock_filename=tests_pipfile_lock)
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/pipenv.py", line 64, in __init__
    super(PipEnvFileParser, self).__init__(pipenv_contents=r.read())
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/pipenv.py", line 54, in __init__
    ext_ref.hashes.add(HashType.from_composite_str(pip_hash))
AttributeError: 'ExternalReference' object has no attribute 'hashes'

======================================================================
ERROR: test_with_multiple_and_no_index (tests.test_parser_pipenv.TestPipEnvParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_pipenv.py", line 42, in test_with_multiple_and_no_index
    parser = PipEnvFileParser(pipenv_lock_filename=tests_pipfile_lock)
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/pipenv.py", line 64, in __init__
    super(PipEnvFileParser, self).__init__(pipenv_contents=r.read())
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/pipenv.py", line 54, in __init__
    ext_ref.hashes.add(HashType.from_composite_str(pip_hash))
AttributeError: 'ExternalReference' object has no attribute 'hashes'

======================================================================
ERROR: test_simple (tests.test_parser_poetry.TestPoetryParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/cyclonedx-python/tests/test_parser_poetry.py", line 30, in test_simple
    parser = PoetryFileParser(poetry_lock_filename=tests_poetry_lock_file)
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/poetry.py", line 61, in __init__
    super(PoetryFileParser, self).__init__(poetry_lock_contents=r.read())
  File "/somewhere/cyclonedx-python/cyclonedx_py/parser/poetry.py", line 44, in __init__
    component.external_references.add(ExternalReference(
AttributeError: 'list' object has no attribute 'add'

----------------------------------------------------------------------
Ran 18 tests in 0.033s

FAILED (errors=6, skipped=1)
```
</details>

However, if I use tox with `poetry run tox -e py -s false` command, it works fine.

<details>
  <summary>Results of running `poetry run tox -e py -s false`</summary>

```bash
$ poetry run tox -e py -s false
.package recreate: /somewhere/cyclonedx-python/.tox/.package
.package installdeps: poetry-core>=1.0.0
py recreate: /somewhere/cyclonedx-python/.tox/py
py installdeps: poetry
py inst: /somewhere/cyclonedx-python/.tox/.tmp/package/1/cyclonedx-bom-3.0.0.tar.gz
py installed: CacheControl==0.12.10,cachy==0.3.0,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.12,cleo==0.8.1,clikit==0.6.2,crashtest==0.3.1,cryptography==36.0.1,cyclonedx-bom @ file:///somewhere/cyclonedx-python/.tox/.tmp/package/1/cyclonedx-bom-3.0.0.tar.gz,cyclonedx-python-lib==2.0.0,distlib==0.3.4,filelock==3.6.0,html5lib==1.1,idna==3.3,importlib-metadata==4.11.1,jeepney==0.7.1,keyring==23.5.0,lockfile==0.12.2,msgpack==1.0.3,packageurl-python==0.9.9,packaging==20.9,pastel==0.2.1,pexpect==4.8.0,pkginfo==1.8.2,platformdirs==2.5.1,poetry==1.1.13,poetry-core==1.0.7,ptyprocess==0.7.0,pycparser==2.21,pylev==1.4.0,pyparsing==3.0.7,requests==2.27.1,requests-toolbelt==0.9.1,SecretStorage==3.3.1,shellingham==1.4.0,six==1.16.0,toml==0.10.2,tomlkit==0.10.0,types-setuptools==57.4.9,types-toml==0.10.4,urllib3==1.26.8,virtualenv==20.13.1,webencodings==0.5.1,zipp==3.7.0
py run-test-pre: PYTHONHASHSEED='7048948125'
py run-test-pre: commands[0] | /somewhere/cyclonedx-python/.tox/py/bin/python --version
Python 3.9.6
py run-test-pre: commands[1] | poetry install --no-root -v
Using virtualenv: /somewhere/cyclonedx-python/.tox/py
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 16 installs, 3 updates, 2 removals, 12 skipped

  • Removing colorama (0.4.4): Skipped for the following reason: Not currently installed
  • Removing importlib-resources (5.4.0): Skipped for the following reason: Not currently installed
  • Removing typed-ast (1.5.2): Skipped for the following reason: Not currently installed
  • Removing importlib-metadata (4.2.0)
  • Removing zipp (3.6.0)
  • Installing distlib (0.3.4): Skipped for the following reason: Already installed
  • Updating filelock (3.6.0 -> 3.4.1)
  • Installing mccabe (0.6.1)
  • Updating platformdirs (2.5.1 -> 2.4.0)
  • Installing pycodestyle (2.8.0)
  • Installing pyflakes (2.4.0)
  • Installing pyparsing (3.0.7): Skipped for the following reason: Already installed
  • Installing six (1.16.0): Skipped for the following reason: Already installed
  • Installing attrs (21.4.0)
  • Installing flake8 (4.0.1)
  • Installing mypy-extensions (0.4.3)
  • Installing packageurl-python (0.9.9): Skipped for the following reason: Already installed
  • Updating packaging (20.9 -> 21.3)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing toml (0.10.2): Skipped for the following reason: Already installed
  • Installing types-setuptools (57.4.9): Skipped for the following reason: Already installed
  • Installing types-toml (0.10.4): Skipped for the following reason: Already installed
  • Installing virtualenv (20.13.1): Skipped for the following reason: Already installed
  • Installing typing-extensions (3.10.0.2)
  • Installing tomli (1.2.3)
  • Installing autopep8 (1.6.0)
  • Installing coverage (6.2)
  • Installing cyclonedx-python-lib (2.0.0): Skipped for the following reason: Already installed
  • Installing flake8-annotations (2.7.0)
  • Installing flake8-bugbear (22.1.11)
  • Installing mypy (0.931)
  • Installing tox (3.24.5)
py run-test: commands[0] | poetry run coverage run --source=cyclonedx_py -m unittest -v
test_conda_list_explicit_md5 (tests.test_parser_conda.TestCondaParser) ... ok
test_conda_list_json (tests.test_parser_conda.TestCondaParser) ... ok
test_simple (tests.test_parser_environment.TestEnvironmentParser)
@todo This test is a vague as it will detect the unique environment where tests are being executed - ... ok
test_simple (tests.test_parser_pipenv.TestPipEnvParser) ... ok
test_with_multiple_and_no_index (tests.test_parser_pipenv.TestPipEnvParser) ... ok
test_simple (tests.test_parser_poetry.TestPoetryParser) ... ok
test_example_1 (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_example_multiline_with_comments (tests.test_parser_requirements.TestRequirementsParser) ... /somewhere/cyclonedx-python/.tox/py/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/specifiers.py:273: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
ok
test_example_with_comments (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_example_with_hashes (tests.test_parser_requirements.TestRequirementsParser) ... skipped 'Not yet supported'
test_example_without_pinned_versions (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_simple (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_parse_conda_json_no_hash (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_no_hash (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_1 (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_2 (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_3 (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_4 (tests.test_utils_conda.TestUtilsConda) ... ok

----------------------------------------------------------------------
Ran 18 tests in 0.194s

OK (skipped=1)
__________________________________________________ summary ___________________________________________________
  py: commands succeeded
  congratulations :)
```
</details>

Let me know if you need more information.

**Comment by madpah** [comment]
Hi @mostafa,

Thanks for the info.

We run tests via `tox` and `poetry`. Can you see whether this results in a better outcome for yourself?

`poetry run tox -epy39`

(With run unittests under Python 3.9)

**Comment by mostafa** [comment]
@madpah It worked, so all good.

<details>
    <summary>Results of running `poetry run tox -epy39`</summary>

```bash
$ poetry run tox -epy39
py39 create: /somewhere/cyclonedx-python/.tox/py39
py39 installdeps: poetry
py39 inst: /somewhere/cyclonedx-python/.tox/.tmp/package/1/cyclonedx-bom-3.0.0.tar.gz
py39 installed: CacheControl==0.12.10,cachy==0.3.0,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.12,cleo==0.8.1,clikit==0.6.2,crashtest==0.3.1,cryptography==36.0.1,cyclonedx-bom @ file:///somewhere/cyclonedx-python/.tox/.tmp/package/1/cyclonedx-bom-3.0.0.tar.gz,cyclonedx-python-lib==2.0.0,distlib==0.3.4,filelock==3.6.0,html5lib==1.1,idna==3.3,importlib-metadata==4.11.1,jeepney==0.7.1,keyring==23.5.0,lockfile==0.12.2,msgpack==1.0.3,packageurl-python==0.9.9,packaging==20.9,pastel==0.2.1,pexpect==4.8.0,pkginfo==1.8.2,platformdirs==2.5.1,poetry==1.1.13,poetry-core==1.0.7,ptyprocess==0.7.0,pycparser==2.21,pylev==1.4.0,pyparsing==3.0.7,requests==2.27.1,requests-toolbelt==0.9.1,SecretStorage==3.3.1,shellingham==1.4.0,six==1.16.0,toml==0.10.2,tomlkit==0.10.0,types-setuptools==57.4.9,types-toml==0.10.4,urllib3==1.26.8,virtualenv==20.13.1,webencodings==0.5.1,zipp==3.7.0
py39 run-test-pre: PYTHONHASHSEED='2633364508'
py39 run-test-pre: commands[0] | /somewhere/cyclonedx-python/.tox/py39/bin/python --version
Python 3.9.6
py39 run-test-pre: commands[1] | poetry install --no-root -v
Using virtualenv: /somewhere/cyclonedx-python/.tox/py39
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 16 installs, 3 updates, 2 removals, 12 skipped

  • Removing colorama (0.4.4): Skipped for the following reason: Not currently installed
  • Removing importlib-resources (5.4.0): Skipped for the following reason: Not currently installed
  • Removing typed-ast (1.5.2): Skipped for the following reason: Not currently installed
  • Removing importlib-metadata (4.2.0)
  • Removing zipp (3.6.0)
  • Installing distlib (0.3.4): Skipped for the following reason: Already installed
  • Updating filelock (3.6.0 -> 3.4.1)
  • Installing mccabe (0.6.1)
  • Updating platformdirs (2.5.1 -> 2.4.0)
  • Installing pycodestyle (2.8.0)
  • Installing pyflakes (2.4.0)
  • Installing pyparsing (3.0.7): Skipped for the following reason: Already installed
  • Installing six (1.16.0): Skipped for the following reason: Already installed
  • Installing attrs (21.4.0)
  • Installing flake8 (4.0.1)
  • Installing mypy-extensions (0.4.3)
  • Installing packageurl-python (0.9.9): Skipped for the following reason: Already installed
  • Updating packaging (20.9 -> 21.3)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing toml (0.10.2): Skipped for the following reason: Already installed
  • Installing tomli (1.2.3)
  • Installing types-setuptools (57.4.9): Skipped for the following reason: Already installed
  • Installing types-toml (0.10.4): Skipped for the following reason: Already installed
  • Installing typing-extensions (3.10.0.2)
  • Installing virtualenv (20.13.1): Skipped for the following reason: Already installed
  • Installing autopep8 (1.6.0)
  • Installing coverage (6.2)
  • Installing cyclonedx-python-lib (2.0.0): Skipped for the following reason: Already installed
  • Installing flake8-annotations (2.7.0)
  • Installing flake8-bugbear (22.1.11)
  • Installing mypy (0.931)
  • Installing tox (3.24.5)
py39 run-test: commands[0] | poetry run coverage run --source=cyclonedx_py -m unittest -v
test_conda_list_explicit_md5 (tests.test_parser_conda.TestCondaParser) ... ok
test_conda_list_json (tests.test_parser_conda.TestCondaParser) ... ok
test_simple (tests.test_parser_environment.TestEnvironmentParser)
@todo This test is a vague as it will detect the unique environment where tests are being executed - ... ok
test_simple (tests.test_parser_pipenv.TestPipEnvParser) ... ok
test_with_multiple_and_no_index (tests.test_parser_pipenv.TestPipEnvParser) ... ok
test_simple (tests.test_parser_poetry.TestPoetryParser) ... ok
test_example_1 (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_example_multiline_with_comments (tests.test_parser_requirements.TestRequirementsParser) ... /somewhere/cyclonedx-python/.tox/py39/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/specifiers.py:273: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
ok
test_example_with_comments (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_example_with_hashes (tests.test_parser_requirements.TestRequirementsParser) ... skipped 'Not yet supported'
test_example_without_pinned_versions (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_simple (tests.test_parser_requirements.TestRequirementsParser) ... ok
test_parse_conda_json_no_hash (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_no_hash (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_1 (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_2 (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_3 (tests.test_utils_conda.TestUtilsConda) ... ok
test_parse_conda_list_str_with_hash_4 (tests.test_utils_conda.TestUtilsConda) ... ok

----------------------------------------------------------------------
Ran 18 tests in 0.079s

OK (skipped=1)
__________________________________________________ summary ___________________________________________________
  py39: commands succeeded
  congratulations :)
```
</details>
