### ISSUE TITLE
bug: conda-parser raises error when unexpected build-number is detected

### ISSUE THREAD

**Issue by DavidLambertCyber** [CycloneDX/cyclonedx-python#331]
## Environment
XUbuntu 20.04
Python 3.8.10
conda 4.12.0 #miniconda
Name: cyclonedx-bom
Version: 3.1.0

## What I did
* update conda base
```
->$ conda update -n base -c defaults conda -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

>$ conda env list
# conda environments:
#
base                  *  /home/fis/miniconda3
```
* Create explicit list 
* [base_spec.txt](https://github.com/CycloneDX/cyclonedx-python/files/8289398/base_spec.txt)
```
>$ conda list -n base --explicit > ./base_spec.txt
```
* Create sbom from explicit list - Error
```
->$ cyclonedx-py -c -i ./base_spec.txt --format json --schema-version 1.3 -o ./conda_base_cyclonedx_1.3_sbom.json
Traceback (most recent call last):
  File "/home/fis/.local/bin/cyclonedx-py", line 8, in <module>
    sys.exit(main())
  File "/home/fis/.local/lib/python3.8/site-packages/cyclonedx_py/client.py", line 260, in main
    CycloneDxCmd(args).execute()
  File "/home/fis/.local/lib/python3.8/site-packages/cyclonedx_py/client.py", line 113, in execute
    output = self.get_output()
  File "/home/fis/.local/lib/python3.8/site-packages/cyclonedx_py/client.py", line 63, in get_output
    parser = self._get_input_parser()
  File "/home/fis/.local/lib/python3.8/site-packages/cyclonedx_py/client.py", line 244, in _get_input_parser
    return CondaListExplicitParser(conda_data=input_data)
  File "/home/fis/.local/lib/python3.8/site-packages/cyclonedx_py/parser/conda.py", line 41, in __init__
    self._parse_to_conda_packages(data_str=conda_data)
  File "/home/fis/.local/lib/python3.8/site-packages/cyclonedx_py/parser/conda.py", line 101, in _parse_to_conda_packages
    conda_package = parse_conda_list_str_to_conda_package(conda_list_str=line)
  File "/home/fis/.local/lib/python3.8/site-packages/cyclonedx_py/utils/conda.py", line 116, in parse_conda_list_str_to_conda_package
    build_number = int(build_number_with_opt_string)
ValueError: invalid literal for int() with base 10: 'main'

->$ cat base_spec.txt | grep "main\." 
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
```

**Comment by jkowalleck** [comment]
Thanks for the detailed report, @DavidLambertCyber. very helpful.
will incorporate the [base_spec.txt](https://github.com/CycloneDX/cyclonedx-python/files/8289398/base_spec.txt) into integration/regression test.

reported root: https://github.com/CycloneDX/cyclonedx-python/blob/master/cyclonedx_py/utils/conda.py#L116
seams like the `build_number_with_opt_string` is not parsed properly.

for the reported "https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda' :
see https://anaconda.org/anaconda/_libgcc_mutex
expected versision: `0.1`
expected  `build_string`: `"main"`
expected ` build_number`: `None`

there are others in the [base_spec.txt](https://github.com/CycloneDX/cyclonedx-python/files/8289398/base_spec.txt), that have the same issue:
* https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-4.5-1_gnu.tar.bz2

**Comment by jkowalleck** [comment]
@DavidLambertCyber ,
thanks to your report the bug was sorted out. version 3.1.1 was just released
