### ISSUE TITLE
poetry lock is no longer working with latest 3.11.2

### ISSUE THREAD

**Issue by matejsp** [CycloneDX/cyclonedx-python#595]
When trying to generate sbom from poetry (latest 1.6.1) lock file it complains:
```
Traceback (most recent call last):
  File "/usr/local/bin/cyclonedx-py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cyclonedx_py/client.py", line 334, in main
    CycloneDxCmd(args).execute()
  File "/usr/local/lib/python3.11/site-packages/cyclonedx_py/client.py", line 147, in execute
    output = self.get_output()
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cyclonedx_py/client.py", line 84, in get_output
    parser = self._get_input_parser()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cyclonedx_py/client.py", line 309, in _get_input_parser
    return PoetryParser(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cyclonedx_py/parser/poetry.py", line 45, in __init__
    poetry_lock_metadata = poetry_lock['metadata']
                           ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'metadata'
ERROR:__main__:Project bts-data-pipelines failed with exception PipBomGeneratorError
```

metada is inside poetry lock file:
```
[metadata]
lock-version = "2.0"
python-versions = ">=3.8.1"
content-hash = "720442e0ed65991874bf38424fb3a10cb3bb9f568a344fed8a91e21a0fb5fcd8"
```

**Comment by matejsp** [comment]
I think we made a mistake by passing pyproject.toml instead of a lock file ... closing
