### ISSUE TITLE
Support implicit post releases

### ISSUE THREAD

**Issue by rback123** [CycloneDX/cyclonedx-python#6]
### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
  
### Current Behavior:

When `cyclonedx-python` encounters an [implicit post release](https://www.python.org/dev/peps/pep-0440/#implicit-post-releases) entry it will crash and won't generate a BOM.

[PEP-0440](https://www.python.org/dev/peps/pep-0440/) declares the two versioning variations to be equivalent.

> **Implicit post releases**
> 
> Post releases allow omitting the post signifier all together. When using this form the separator MUST be - and no other form is allowed. This allows versions such as 1.0-1 to be normalized to 1.0.post1. This particular normalization MUST NOT be used in conjunction with the implicit post release number rule. In other words, 1.0- is not a valid version and it does not normalize to 1.0.post0.

It seems that pip uses the `3.2.3.post2` format in the frozen requirements file and the PyPi restful web service responses use the `3.2.3-2` format. PyPi accepts either format, per the spec.

### Steps to Reproduce (if defect):

For example, see  `functools32` (requires python 2.7) currently version `3.2.3-2` https://pypi.org/project/functools32/#history. 
```
$ curl -s https://pypi.org/pypi/functools32/json | python -m json.tool | grep "\"version\":"
        "version": "3.2.3-2"
```

Release versions:
```
$ curl -s https://pypi.org/pypi/functools32/json | python -m json.tool
...
    "releases": {
        "3.2.3": [],
...
        "3.2.3-1": [
...
        "3.2.3-2": [
...
```

#### Generate the Requirements file

1. Load library and generate a requirements file
```
$ pip install functools32
$ pip freeze > requirements_default.txt
```
2. Note the version is listed as `3.2.3.post2`
```
$ cat requirements_default.txt
functools32==3.2.3.post2
```

#### Reproduce the error

1. Run CycloneDX
```
$ cyclonedx-py -i requirements_default.txt 
Input file: requirements_default.txt
Output BOM: bom.xml
Generating CycloneDX BOM
Traceback (most recent call last):
  File "/tmp/cyclone/cycdx/bin/cyclonedx-py", line 10, in <module>
    sys.exit(main())
  File "/tmp/cyclone/cycdx/lib/python3.6/site-packages/cyclonedx/cli/generateBom.py", line 69, in main
    version_release = releases[version]
KeyError: '3.2.3.post2'
```

The "releases" array was displayed above and the keys were in implicit version string format.

### Expected Behavior:

It should treat `3.2.3.post2` the same as `3.2.3-2`.

### Environment:
  
  - cyclonedx-bom Version: 0.2.0
  - python Version: 3.6.7

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Possibly check for implicit version strings if there is a KeyError when working with the PyPi response?

#### Verify PyPi works with either format

The etag HTTP response header is the same value with either format so internally PyPi treats both version strings as the same resource.

Post format
```
$ curl -s --head https://pypi.org/pypi/functools32/3.2.3.post2/json | grep "etag:"
etag: "TvkoNOBe/zwpNL1J9zhKjg"
```

Implicit format
```
$ curl -s --head https://pypi.org/pypi/functools32/3.2.3-2/json | grep "etag:"
etag: "TvkoNOBe/zwpNL1J9zhKjg"
```

**Comment by rback123** [comment]
One library that might help is [packaging](https://packaging.pypa.io/en/latest/version/).


Here is another example: 
```
$ cat ibm_requirements.txt 
ibm-db-sa-py3==0.3.1.post1

$ cyclonedx-py -i ibm_requirements.txt 
Input file: ibm_requirements.txt
Output BOM: bom.xml
Generating CycloneDX BOM
Traceback (most recent call last):
  File "/private/tmp/testing_pip/bin/cyclonedx-py", line 10, in <module>
    sys.exit(main())
  File "/private/tmp/testing_pip/lib/python2.7/site-packages/cyclonedx/cli/generateBom.py", line 69, in main
    version_release = releases[version]
KeyError: '0.3.1.post1'

# note 0.3.1.post1 is not in pypi response
$ curl -s https://pypi.org/pypi/ibm-db-sa-py3/json | python -m json.tool | grep -e "0.3.1.post1"

# note 0.3.1-1 is in pypi response
$ curl -s https://pypi.org/pypi/ibm-db-sa-py3/json | python -m json.tool | grep -e "0.3.1-1"
        "release_url": "https://pypi.org/project/ibm-db-sa-py3/0.3.1-1/",
        "version": "0.3.1-1"
                "filename": "ibm-db-sa-py3-0.3.1-1.tar.gz",
                "url": "https://files.pythonhosted.org/packages/41/cf/8c6a9da71671f9e661036929533ec92dd672b61032a4c585926529b0da24/ibm-db-sa-py3-0.3.1-1.tar.gz"
        "0.3.1-1": []
```
