### ISSUE TITLE
cyclonedx-py fails on strange requirements.txt

### ISSUE THREAD

**Issue by pklotz** [CycloneDX/cyclonedx-python#7]
Hi,

cyclonedx-py fails on a requirements.txt, when called like this:

$ cyclonedx-py -i requirements.txt -o bom.xml
Traceback (most recent call last):
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 1384, in connect
    super().connect()
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 932, in connect
    self._tunnel()
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 906, in _tunnel
    (version, code, message) = response._read_status()
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\site-packages\xmlschema\validators\schema.py", line 218, in __init__
    self.source = XMLResource(source, base_url, defuse, timeout, lazy=False)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\site-packages\xmlschema\resources.py", line 240, in __init__
    self.source = source
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\site-packages\xmlschema\resources.py", line 264, in __setattr__
    self._root, self._document, self._text, self._url = self._fromsource(value)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\site-packages\xmlschema\resources.py", line 342, in _fromsource
    resource = urlopen(url, timeout=self.timeout)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Remote end closed connection without response>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\klp1wa3\AppData\Local\Programs\Python\Python37-32\Scripts\cyclonedx-py.exe\__main__.py", line 5, in <module>
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\site-packages\cyclonedx\cli\generateBom.py", line 23, in <module>
    from cyclonedx import BomValidator
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\site-packages\cyclonedx\BomValidator.py", line 19, in <module>
    bom_schema = xmlschema.XMLSchema("http://cyclonedx.org/schema/bom/1.0")
  File "c:\users\klp1wa3\appdata\local\programs\python\python37-32\lib\site-packages\xmlschema\validators\schema.py", line 220, in __init__
    raise type(err)('cannot create schema: %s' % err)
urllib.error.URLError: <urlopen error cannot create schema: <urlopen error Remote end closed connection without response>>

The requirements.txt looks a bit weird but seems to valid, see URL to blog post as comment:

$ cat requirements.txt
--index-url https://pypi.python.org/simple/

-e .
# see https://caremad.io/posts/2013/07/setup-vs-requirement/ for more information on -e . ..
$

Is this something in the tool or in my environment?
Any idea? Thanks,

Peter

**Comment by stevespringett** [comment]
Is it possible to post the requirements.txt file? If not, perhaps send via email?

**Comment by stevespringett** [comment]
Oh never mind. Can you confirm that this is the contents of requirements.txt?

```
--index-url https://pypi.python.org/simple/
```

**Comment by pklotz** [comment]
Hi Steve, sorry the requirements.txt was contained at the end of my post above.
The problem seems to be the "-e ."
But when I remove this, I get a bom, though an empty one

**Comment by madpah** [comment]
@pklotz - is this still and issue?

If so, would appreciate a fresh post of the `requirements.txt` that was causing the failure.

**Comment by madpah** [comment]
Closing due to inactivity. Please re-open if this is still an issue for you.
