### ISSUE TITLE
[BUG] http dependency wrongly parsed

### ISSUE THREAD

**Issue by the-glu** [CycloneDX/cyclonedx-python#715]
## Describe the bug

It seems that some http dependency are not correctly parsed, crashing cyclonedx

```
cyclonedx-py environment /www/gestion/virtualenvs/main/ -vvv
DEBUG    | CDX > args: {'command': 'environment', 'pyproject_file': None, 'mc_type': <ComponentType.APPLICATION: 'application'>, 'python': '/www/gestion/virtualenvs/main/', 'short_purls': False, 'outfile': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, 'schema_version': <SchemaVersion.V1_5: (1, 5)>, 'output_format': <OutputFormat.JSON: 1>, 'output_reproducible': False, 'should_validate': True, '_bbc': <class 'cyclonedx_py._internal.environment.EnvironmentBB'>}
INFO     | CDX > Generating SBOM ...
DEBUG    | CDX.EnvironmentBB > fetch `path` from python interpreter cmd: ('/www/gestion/virtualenvs/main/bin/python', '-c', 'import json,sys;json.dump(sys.path,sys.stdout)')
DEBUG    | CDX.EnvironmentBB > got `path` from Python interpreter: '["", "/usr/lib/python39.zip", "/usr/lib/python3.9", "/usr/lib/python3.9/lib-dynload", "/www/gestion/virtualenvs/main/lib/python3.9/site-packages", "/www/gestion/git-repo/arcanite-gestion"]'
DEBUG    | CDX.EnvironmentBB > distribution context args: {'path': ['/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/www/gestion/virtualenvs/main/lib/python3.9/site-packages', '/www/gestion/git-repo/arcanite-gestion']}
INFO     | CDX.EnvironmentBB > discovering distributions...
INFO     | CDX.EnvironmentBB > add component for package 'amqp'
DEBUG    | CDX.EnvironmentBB > add component: <Component bom-ref=<BomRef 'amqp==5.2.0' id=140004126494576>, group=None, name=amqp, version=5.2.0, type=library>
INFO     | CDX.EnvironmentBB > add component for package 'urllib3'
DEBUG    | CDX.EnvironmentBB > add component: <Component bom-ref=<BomRef 'urllib3==1.26.15' id=140004126494480>, group=None, name=urllib3, version=1.26.15, type=library>
INFO     | CDX.EnvironmentBB > add component for package 'sshpubkeys'
DEBUG    | CDX.EnvironmentBB > add component: <Component bom-ref=<BomRef 'sshpubkeys==3.3.1' id=140004126469136>, group=None, name=sshpubkeys, version=3.3.1, type=library>
INFO     | CDX.EnvironmentBB > add component for package 'Unidecode'
DEBUG    | CDX.EnvironmentBB > add component: <Component bom-ref=<BomRef 'Unidecode==1.3.8' id=140004126469520>, group=None, name=Unidecode, version=1.3.8, type=library>
INFO     | CDX.EnvironmentBB > add component for package 'wcwidth'
DEBUG    | CDX.EnvironmentBB > add component: <Component bom-ref=<BomRef 'wcwidth==0.2.13' id=140004125301632>, group=None, name=wcwidth, version=0.2.13, type=library>
DEBUG    | CDX > Error: list index out of range
Traceback (most recent call last):
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/cli.py", line 289, in run
    Command(**args, logger=logger)(**args)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/cli.py", line 251, in __call__
    bom = self._make_bom(**kwargs)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/cli.py", line 246, in _make_bom
    return self._bbc(**self._clean_kwargs(kwargs))
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/environment.py", line 147, in __call__
    self.__add_components(bom, rc, path=path)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/environment.py", line 171, in __add_components
    self.__component_add_extred_and_purl(component, packagesource4dist(dist))
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/utils/pep610.py", line 111, in packagesource4dist
    return PackageSourceArchive.from_data(url, subdirectory, data['archive_info'])
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/utils/pep610.py", line 76, in from_data
    hashes = {hash_parts[0]: hash_parts[1]}
IndexError: list index out of range
CRITICAL | CDX > list index out of range
```

I added a print just before the lignes to display `info`: `{'hash': 'sha256:b0a729154e33dfcc109d3e11d4655583e8284b41bf3fff6bcaa8762b2f5009a4'}`

This match the following line returned by `pip freeze`:

`packagename @ https://somewhere/packagename.tar.gz#sha256:b0a729154e33dfcc109d3e11d4655583e8284b41bf3fff6bcaa8762b2f5009a4`

## To Reproduce

I tried but I was not able to create an example with the same format when I do a pip freeze. The package is an old internal library that I cannot really share, and when I tried in a new virtual env, the url doesn't have the #sha256, just the URL.

I also tried to pip uninstall the faulty package and reinstall it: the hash was removed and cyclonedx is working fine.

## Expected behavior

I would assume since I cannot recreate a demo virutalenv that it's dues to a combination of old install / random old version of poetry / pip / setuptools that leaded to a `packagename @ https://somewhere/packagename.tar.gz#sha256:hash` line and there is no real need to support the specific output, but it would be better if cyclone was not crashing on thoses lines.

## Environment

- _cyclonedx-py_ version: 4.1.5
- Python version: 3.9.2
- OS: debian 11
- poetry 1.8.x

**Comment by jkowalleck** [comment]
issue is caused by a outdated/deprecated method of python internals on how storing hashes worked: https://packaging.python.org/en/latest/specifications/direct-url-data-structure/#archive-urls 

will provide a fix that might help you there.

**Comment by jkowalleck** [comment]
@the-glu could you check [version 4.1.6](https://github.com/CycloneDX/cyclonedx-python/releases/tag/v4.1.6)? It should include a modification which prevents the tool from crashing in your setup.

**Comment by the-glu** [comment]
I can confirm it does work, thanks for the quick fix :)
