### ISSUE TITLE
[BUG] (Old) celery's dependency crash parser

### ISSUE THREAD

**Issue by the-glu** [CycloneDX/cyclonedx-python#717]
## Describe the bug

Celery 5.1.2 (at least) has a dependency specified as "Requires-Dist: pytz (>dev)"

This crash cyclonedx:

```
DEBUG    | CDX > Error: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^
Traceback (most recent call last):
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/_parser.py", line 217, in _parse_specifier
    tokenizer.consume("WS")
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/_tokenizer.py", line 187, in enclosing_tokens
    self.raise_syntax_error(
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/cli.py", line 289, in run
    Command(**args, logger=logger)(**args)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/cli.py", line 251, in __call__
    bom = self._make_bom(**kwargs)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/cli.py", line 246, in _make_bom
    return self._bbc(**self._clean_kwargs(kwargs))
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/environment.py", line 147, in __call__
    self.__add_components(bom, rc, path=path)
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/cyclonedx_py/_internal/environment.py", line 175, in __add_components
    tuple(map(Requirement, dist.requires or ()))
  File "/opt/gestion_package_checks_sbom_collector_and_uploader/lib/python3.9/site-packages/packaging/requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^
CRITICAL | CDX > Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
```

## To Reproduce

```sh
#!/bin/bash
python3 -m venv test
source test/bin/active
pip install celery==5.1.2 cyclonedx-bom
cyclonedx-py environment
```

## Expected behavior

As previous bug I'm not sure it's a spec-ok dependency, but it would be great if cyclonedx at least ignore thoses lines :)

## Environment

* cyclonedx-py version: 4.1.6
* Python version: 3.9.2
* OS: debian 11

**Comment by jkowalleck** [comment]
celery 5.1.2 https://pypi.org/project/celery/5.1.2/#files

wheel defines:
<details><summary>Details</summary>
<p>
```text
Metadata-Version: 2.1
Name: celery
Version: 5.1.2
Summary: Distributed Task Queue.
Home-page: http://celeryproject.org
Author: Ask Solem
Author-email: auvipy@gmail.com
License: BSD
Project-URL: Documentation, http://docs.celeryproject.org/en/latest/index.html
Project-URL: Code, https://github.com/celery/celery
Project-URL: Tracker, https://github.com/celery/celery/issues
Project-URL: Funding, https://opencollective.com/celery
Keywords: task job queue distributed messaging actor
Platform: any
Classifier: Development Status :: 5 - Production/Stable
Classifier: License :: OSI Approved :: BSD License
Classifier: Topic :: System :: Distributed Computing
Classifier: Topic :: Software Development :: Object Brokering
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 3 :: Only
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: Implementation :: CPython
Classifier: Programming Language :: Python :: Implementation :: PyPy
Classifier: Operating System :: OS Independent
Requires-Python: >=3.6,
License-File: LICENSE
Requires-Dist: pytz (>dev)
Requires-Dist: billiard (<4.0,>=3.6.4.0)
Requires-Dist: kombu (<6.0,>=5.1.0)
Requires-Dist: vine (<6.0,>=5.0.0)
Requires-Dist: click (<8.0,>=7.0)
Requires-Dist: click-didyoumean (>=0.0.3)
Requires-Dist: click-repl (>=0.1.6)
Requires-Dist: click-plugins (>=1.1.1)
Requires-Dist: setuptools
Provides-Extra: arangodb
Requires-Dist: pyArango (>=1.3.2) ; extra == 'arangodb'
Provides-Extra: auth
Requires-Dist: cryptography ; extra == 'auth'
Provides-Extra: azureblockblob
Requires-Dist: azure-storage-blob (==12.6.0) ; extra == 'azureblockblob'
Provides-Extra: brotli
Requires-Dist: brotli (>=1.0.0) ; (platform_python_implementation == "CPython") and extra == 'brotli'
Requires-Dist: brotlipy (>=0.7.0) ; (platform_python_implementation == "PyPy") and extra == 'brotli'
Provides-Extra: cassandra
Requires-Dist: cassandra-driver (<3.21.0) ; extra == 'cassandra'
Provides-Extra: consul
Requires-Dist: python-consul2 ; extra == 'consul'
Provides-Extra: cosmosdbsql
Requires-Dist: pydocumentdb (==2.3.2) ; extra == 'cosmosdbsql'
Provides-Extra: couchbase
Requires-Dist: couchbase (>=3.0.0) ; (platform_python_implementation != "PyPy") and extra == 'couchbase'
Provides-Extra: couchdb
Requires-Dist: pycouchdb ; extra == 'couchdb'
Provides-Extra: django
Requires-Dist: Django (>=1.11) ; extra == 'django'
Provides-Extra: dynamodb
Requires-Dist: boto3 (>=1.9.178) ; extra == 'dynamodb'
Provides-Extra: elasticsearch
Requires-Dist: elasticsearch ; extra == 'elasticsearch'
Provides-Extra: eventlet
Requires-Dist: eventlet (>=0.26.1) ; extra == 'eventlet'
Provides-Extra: gevent
Requires-Dist: gevent (>=1.0.0) ; extra == 'gevent'
Provides-Extra: librabbitmq
Requires-Dist: librabbitmq (>=1.5.0) ; extra == 'librabbitmq'
Provides-Extra: memcache
Requires-Dist: pylibmc ; (platform_system != "Windows") and extra == 'memcache'
Provides-Extra: mongodb
Requires-Dist: pymongo[srv] (>=3.3.0) ; extra == 'mongodb'
Provides-Extra: msgpack
Requires-Dist: msgpack ; extra == 'msgpack'
Provides-Extra: pymemcache
Requires-Dist: python-memcached ; extra == 'pymemcache'
Provides-Extra: pyro
Requires-Dist: pyro4 ; extra == 'pyro'
Provides-Extra: pytest
Requires-Dist: pytest-celery ; extra == 'pytest'
Provides-Extra: redis
Requires-Dist: redis (>=3.2.0) ; extra == 'redis'
Provides-Extra: s3
Requires-Dist: boto3 (>=1.9.125) ; extra == 's3'
Provides-Extra: slmq
Requires-Dist: softlayer-messaging (>=1.0.3) ; extra == 'slmq'
Provides-Extra: solar
Requires-Dist: ephem ; (platform_python_implementation != "PyPy") and extra == 'solar'
Provides-Extra: sqlalchemy
Requires-Dist: sqlalchemy ; extra == 'sqlalchemy'
Provides-Extra: sqs
Requires-Dist: boto3 (>=1.9.125) ; extra == 'sqs'
Requires-Dist: pycurl (==7.43.0.5) ; extra == 'sqs'
Provides-Extra: tblib
Requires-Dist: tblib (>=1.3.0) ; (python_version < "3.8.0") and extra == 'tblib'
Requires-Dist: tblib (>=1.5.0) ; (python_version >= "3.8.0") and extra == 'tblib'
Provides-Extra: yaml
Requires-Dist: PyYAML (>=3.10) ; extra == 'yaml'
Provides-Extra: zookeeper
Requires-Dist: kazoo (>=1.3.1) ; extra == 'zookeeper'
Provides-Extra: zstd
Requires-Dist: zstandard ; extra == 'zstd'
```
</p>
</details> 

relevant part: 
> `Requires-Dist: pytz (>dev)`

**Comment by jkowalleck** [comment]
i will check whether this version of `celery` is installable at all.
if this is all due to an invalid non-yanked version of `celery`, the i will not bother finding a workaround.

**Comment by jkowalleck** [comment]
FYI: Installation with pip 24.0 shows:
```
DEPRECATION: celery 5.1.2 has a non-standard dependency specifier pytz>dev. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of celery or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

**Comment by jkowalleck** [comment]
Dug into the details, and I tend to not fix this at all.
The release of `celery 5.1.2` was invalid, the dependency declaration was malformed and some tools tried to make sense of it.
This does not mean others should follow this example - and therefore `cyclonedx-py` will not introduce a fix nor alter its behavior.


options considered:
- implement an own requirements-parser that "ignores" the issue.  
  From a process, ignoring the invalid version number would be okay, since the dependency-version number is irrelevant. only dependency name and extras matter at this point there.
  but i just do not want to introduce yet another immature parser for a thing that has been solved already (by package `packaging` which has a PEP440 compliant parser), sole for the reason of one package (`celery`) that did wrong in the past. 
- warn about unpassable dependency and ignore it in SBOM.
  THis is the works to happen. This wold result in incomplete SBOM data. not intended at all.
